### ISSUE TITLE
Do I have to connect the hub before?

### ISSUE THREAD

**Issue by TravelTrader** [noamraph/mindstorms#1]
Hello Noam,
this would be awesome to connect and code the hub under Linux.
But I couldn't get it work. Do I have to connect the hub before by another tool? Or just plugin USB or start bluetooth?
I ask because there's not even a connection.

Would be great to get any help by you.
Thank you!

Update: I get the error `rshell.pyboard.PyboardError: failed to access /dev/ttyACM0`.

**Comment by noamraph** [comment]
Hi,
See https://forum.arduino.cc/t/permission-denied-on-dev-ttyacm0/475568/3
I think you should remove the modem-manager package, and add yourself to the "dialout" group. Reboot, and check if it works.

**Comment by TravelTrader** [comment]
The `/dev/ttyACM*` showed:
`crw-rw---- 1 root dialout 166, 0 Feb 16 19:15 /dev/ttyACM0`

So I added me as user to the group by `sudo adduser $USER dialout`.

Then rebooted and ... thank you so much! It works!
I cannot write down how happy I am about it. Great support.

**Comment by noamraph** [comment]
Great! Let me know how it goes!

**Comment by TravelTrader** [comment]
Works great. Thanks a lot!

Would there be a possibility to use bluetooth instead of usb?
And do you know about the port data of the sensors?

**Comment by noamraph** [comment]
@TravelTrader Bluetooth should work if you manage to get the serial port over bluetooth. It didn't work for me. If it works, you can just pass the device name (`/dev/rfcomm0` or something like that) to `Hub()`.

I found a library, spikedev, that allows reading of the sensors. I patched it a bit, and added a note on README.md on how to use it.
