### ISSUE TITLE
Not able to control motors

### ISSUE THREAD

**Issue by kir486680** [noamraph/mindstorms#3]
I am trying to just perform a simple motor rotation using this code 

```
from mindstorms import Hub
hub = Hub()
motor = hub.port.E.motor
print(motor)
motor.run_for_degrees(270)
```
However, I get this error `rshell.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nAttributeError: \'NoneType\' object has no attribute \'run_for_degrees\'\r\n') 
`
However, when I am trying to run it as a separate file, it gives me the error. In addition, this error also appears with all motor movement methods. The print motor statement returns `hub.port.E.motor`, which seems to be correct. This code works if I perform it line by line in the python terminal. I do not really understand why this would be the case.

**Comment by kir486680** [comment]
Some updates regarding this issue. 
```
    device = find_device()
    board = Pyboard(device)
    board.enter_raw_repl()
    print(board.exec_("import hub;print(hub.port.A.motor)"))
```
This code also yields the same issue.

**Comment by sombody2281337** [comment]
I have the same issue! When I run my code in Python shell, everything works. It does not work as a .py file tho

**Comment by kir486680** [comment]
Found the solution. Just need to add time.sleep(1) after the hub initialization
