### ISSUE TITLE
Advice on what am I doing wrong

### ISSUE THREAD

**Issue by crypto-titan** [noamraph/mindstorms#4]
Hey Noam,

I am a DevOps engineer and I can code in Node.js but I never used Python before. 
Probably I am doing something pretty basic wrong, can you point me to the right direction? 

<img width="1727" alt="Screenshot at Jan 06 16-36-30" src="https://user-images.githubusercontent.com/17948972/211045243-fec2bf37-3076-4436-a8d1-3ee7ed20dfac.png">

**Comment by crypto-titan** [comment]
if I use the python console it works, it only does not work if I call it as a file

**Comment by williamcorsel** [comment]
I noticed that setting the motor mode using `.mode` fails when executed too quickly after starting the hub connection. Possibly due to some setup that happens with the motors. For me, it helps to wait around 1 second after starting the hub connection before accessing motors.

Also see #3

**Comment by crypto-titan** [comment]
thank you!
