### ISSUE TITLE
USB device not found

### ISSUE THREAD

**Issue by mh-g** [noamraph/mindstorms#8]
When trying "hub=Hub()", I get the error "Couldn't find USB device". Connecting with MINDSTORMS EV3 Home Edition or Visual Studio Code and EV3 Micropython extension works fine.

The mindstorms.py file lists USB_VID 0x0694 and USB_PID 0x0010, but my device has USB_PID 0x0005, even after a firmware upgrade to V1.09H.

This is the sysinfo output of VSCode:
```
========== ev3dev-sysinfo ==========
Image file:         ev3-micropython-v2.0.0-sd-card-image
Kernel version:     4.14.117-ev3dev-2.3.5-ev3
Brickman:           0.10.3
BogoMIPS:           148.88
Bluetooth:          2.1
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165341CC9B
BOARD_INFO_TYPE=main
```

Is this firmware not supported? There seems a USB_PID 0x0006 for an updated firmware as well, but I could not find any newer version than the 1.09H that I got (direct link from LEGO website).

**Comment by noamraph** [comment]
Hi, the code only works with robot inventor, and probably spike. Sorry!
